@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":CancelMeetingCommandParser" as CancelMeetingCommandParser LOGIC_COLOR
participant "cmc:CancelMeetingCommand" as CancelMeetingCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("cancel 1 mi/1 ")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("cancel 1 mi/1 ")
activate AddressBookParser

create CancelMeetingCommandParser
AddressBookParser -> CancelMeetingCommandParser
activate CancelMeetingCommandParser

CancelMeetingCommandParser --> AddressBookParser
deactivate CancelMeetingCommandParser

AddressBookParser -> CancelMeetingCommandParser : parse("1 mi/1")
activate CancelMeetingCommandParser

create CancelMeetingCommand
CancelMeetingCommandParser -> CancelMeetingCommand
activate CancelMeetingCommand

CancelMeetingCommand --> CancelMeetingCommandParser :
deactivate CancelMeetingCommand

CancelMeetingCommandParser --> AddressBookParser : rc
deactivate CancelMeetingCommandParser

destroy CancelMeetingCommandParser

AddressBookParser --> LogicManager : rc
deactivate AddressBookParser

LogicManager -> CancelMeetingCommand : execute(m)
activate CancelMeetingCommand

CancelMeetingCommand -> Model : setPerson(1, editedPerson)
activate Model

Model --> CancelMeetingCommand
deactivate Model

create CommandResult
CancelMeetingCommand -> CommandResult
activate CommandResult

CommandResult --> CancelMeetingCommand
deactivate CommandResult

CancelMeetingCommand --> LogicManager : r
deactivate CancelMeetingCommand

[<--LogicManager
deactivate LogicManager
@enduml
