@startuml
!include style.puml
!pragma useVerticalIf on
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

start
:Increment person's status command;
if () then ([else])
    :Output invalid person index error;
( [index in list]) elseif () then ([else])
    :Output person not client error;
( [person is client]) elseif () then ([else])
    :Output max status error;
else ( [status can increment])
    :Create person with incremented status;
:Replace old person in list with new person;
endif
stop

@enduml