@startuml
!include style.puml
show fields
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

class P as "Person"

class Me as "Meeting" {
  meetingDate: LocalDate
  meetingTime: LocalTime
  agenda: String
  duration: Duration
  notes: String
}


P-->"0..5"Me

hide P members

@enduml
